/* Generated by vpassert; File:"verilog/pli.v" */
`line 1 "verilog/pli.v" 0
// DESCRIPTION: Example pli file for vpassert program
// This file ONLY is placed into the Public Domain, for any use,
// without warranty, 2000-2012 by Wilson Snyder.

`timescale 1ns/1ns

module pli;/*vpassert beginmodule pli*/
   // A module called PLI is required, to contain the error counts
   // This is required with the vpassert --nostop option, which this example uses
   // By default (--stop), this file isn't needed at all

   integer errors; initial errors = 0;
   integer warnings; initial warnings = 0;

   // Normally this would be 0 at startup, then become 1 after reset deasserts
   // This prevents false assertion checks during reset
   integer message_on; initial message_on = 1;

   always @ (errors or warnings) begin
`ifdef OPTIONAL_EXIT_ON_WARNING
      if (errors!=0 || warnings!=0) begin
	 
/*VCS coverage off*/
/*ax_line_coverage_off*/
/*vpassert*/begin /*verilator coverage_block_off*/begin $write ("[%0t] -I:pli.v:0022:           Errors/warnings found, exiting!\n",$time); end end /*vpassert*/
/*VCS coverage on*/
/*ax_line_coverage_on*/
`line 22 "verilog/pli.v" 0

	 $finish;
      end
`else
`line 24 "verilog/pli.v" 0

/*VCS coverage off*/
/*ax_line_coverage_off*/
/*verilator coverage_off*/
/*vpassert*/
`line 25 "verilog/pli.v" 0

      if (errors!=0) begin
	 begin begin $write ("[%0t] -I:pli.v:0027:           Errors found, exiting!\n",$time); end end 
	 $finish;
      end
      else if (warnings!=0) begin
	 begin begin $write ("[%0t] -I:pli.v:0031:           Warnings found, consider stopping!\n",$time); end end 
      end
`line 31 "verilog/pli.v" 0
/*vpassert*/
/*verilator coverage_on*/
/*VCS coverage on*/
/*ax_line_coverage_on*/
`line 32 "verilog/pli.v" 0

`endif
   end

endmodule
`line 37 "verilog/pli.v" 0

