/* Generated by vpassert; File:"verilog/pli.v" */
`line 1 "verilog/pli.v" 0
// DESCRIPTION: Example pli file for vpassert program
// This file ONLY is placed into the Public Domain, for any use,
// without warranty, 2000-2012 by Wilson Snyder.

`timescale 1ns/1ns

module pli;/*vpassert beginmodule pli*/
   // A module called PLI is required, to contain the error counts
   // This is required with the vpassert --nostop option, which this example uses
   // By default (--stop), this file isn't needed at all

   integer errors; initial errors = 0;
   integer warnings; initial warnings = 0;

   // Normally this would be 0 at startup, then become 1 after reset deasserts
   // This prevents false assertion checks during reset
   integer message_on; initial message_on = 1;

   always @ (errors or warnings) begin
`ifdef OPTIONAL_EXIT_ON_WARNING
      if (errors!=0 || warnings!=0) begin
	 
/*VCS coverage off*/
/*vpassert*/begin /*verilator coverage_block_off*/begin $callInfo ("Errors/warnings found, exiting!\n"); end end /*vpassert*/
/*VCS coverage on*/
`line 22 "verilog/pli.v" 0

	 $finish;
      end
`else
      if (errors!=0) begin
	 
/*VCS coverage off*/
/*vpassert*/begin /*verilator coverage_block_off*/begin $callInfo ("Errors found, exiting!\n"); end end /*vpassert*/
/*VCS coverage on*/
`line 27 "verilog/pli.v" 0

	 $finish;
      end
      else if (warnings!=0) begin
	 
/*VCS coverage off*/
/*vpassert*/begin /*verilator coverage_block_off*/begin $callInfo ("Warnings found, consider stopping!\n"); end end /*vpassert*/
/*VCS coverage on*/
`line 31 "verilog/pli.v" 0

      end
`endif
   end

endmodule
`line 37 "verilog/pli.v" 0

